🐛 HOTFIX 4: Comment volume_discount_tiers query - table doesn't exist
ERROR: Table 'volume_discount_tiers' doesn't exist
- Commented out volume discount tier logic
- Commented lines will be enabled once table is added to schema

CRITICAL FIX: Resolves ER_NO_SUCH_TABLE error